# Generated by Django 5.0.6 on 2024-06-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_announcement_media_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
