# Generated by Django 5.0.6 on 2024-06-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_announcement_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
