# Generated by Django 5.0.6 on 2024-06-02 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_announcement_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=models.TextField(default='blank'),
            preserve_default=False,
        ),
    ]
